Add polyfills for ChildNode APIs.
webcomponents/polyfills pull request #390
Opened 2020-10-07 22:32 UTC by bicknellr

2020-10-08 19:08 UTC, bicknellr commented on packages/shadydom/src/patch-prototypes.js
> +  DocumentType: [ChildNodePatches],
Maybe it isn't worth trying to make this work on `DocumentType`. Testing it is pretty awkward and the restrictions on where a `DocumentType` can go in a document (only first child of a document, maybe?) and what can go around one (almost nothing except comments and a single following `<html>`?) makes the ChildNode APIs on DocumentType pretty useless.

2020-10-08 19:08 UTC, bicknellr commented on packages/shadydom/src/patches/ChildNode.js
> +  },
I need to check the order here since this probably feeds into `MutationObserver`s. Likely, this should be remove first, then insert new children.

2020-10-12 18:52 UTC, sorvell requested changes

2020-10-12 18:52 UTC, sorvell commented on packages/tests/webcomponentsjs_/child-node/after.html
> +      delete item.after;
Why do you have to do this?

2020-10-12 18:52 UTC, sorvell commented on packages/tests/webcomponentsjs_/child-node/after.html
> +    const testBefore = (createChildNode) => {
testAfter?

2020-10-12 18:52 UTC, sorvell commented on packages/tests/webcomponentsjs_/child-node/before.html
> +      delete item.before;
Again, why is this here?

2020-10-12 18:52 UTC, sorvell commented on packages/tests/webcomponentsjs_/child-node/remove.html
> +      delete item.remove;
Again, why is this here?

2020-10-12 18:52 UTC, sorvell commented on packages/tests/webcomponentsjs_/child-node/replace-with.html
> +      delete item.replaceWith;
Again, why is this here?

2020-10-15 19:50 UTC, sorvell approved these changes

2020-10-15 20:37 UTC, merged